### ISSUE TITLE
Evaluation failed: TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by nelson-liu** [gildas-lormeau/single-filez-cli#7]
Hi!

Thanks for creating single-filez-cli . I'm sometimes running into random errors with `single-filez-cli` that `single-file-cli` does not seem to struggle with. For example:

```
$ docker run singlefilez https://www.walmart.com/c/kp/replace-hubcaps
Evaluation failed: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at za (<anonymous>:1:88045)
    at <anonymous>:1:90843
    at Array.forEach (<anonymous>)
    at za (<anonymous>:1:88131)
    at <anonymous>:1:90843
    at Array.forEach (<anonymous>)
    at za (<anonymous>:1:88131)
    at <anonymous>:1:90843
    at Array.forEach (<anonymous>) URL: https://www.walmart.com/c/kp/replace-hubcaps
Stack: Error: Evaluation failed: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at za (<anonymous>:1:88045)
    at <anonymous>:1:90843
    at Array.forEach (<anonymous>)
    at za (<anonymous>:1:88131)
    at <anonymous>:1:90843
    at Array.forEach (<anonymous>)
    at za (<anonymous>:1:88131)
    at <anonymous>:1:90843
    at Array.forEach (<anonymous>)
    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async getPageData (/usr/src/app/node_modules/single-filez-cli/back-ends/puppeteer.js:150:20)
    at async exports.getPageData (/usr/src/app/node_modules/single-filez-cli/back-ends/puppeteer.js:56:10)
    at async capturePage (/usr/src/app/node_modules/single-filez-cli/single-file-cli-api.js:239:20)
    at async runNextTask (/usr/src/app/node_modules/single-filez-cli/single-file-cli-api.js:156:20)
    at async Promise.all (index 0)
    at async capture (/usr/src/app/node_modules/single-filez-cli/single-file-cli-api.js:126:2)
    at async run (/usr/src/app/node_modules/single-filez-cli/single-filez:57:2)
```

Do you have a sense of what might be wrong? Thanks in advance!

**Comment by gildas-lormeau** [comment]
Thank you for the report. I was able to reproduce and fix the bug. The fix will be available in the next version.

**Comment by nelson-liu** [comment]
thank you!

**Comment by gildas-lormeau** [comment]
You're welcome. FYI, the new version is available on npm.
